// Plain-language definitions of loyalty and finance terms.
export const GLOSSARY = [
  { term: 'Active member', def: 'A member who participates in a financially meaningful way—not just someone who signed up. Active members are what drive loyalty ROI.' },
  { term: 'Average order value (AOV)', def: 'The average amount a customer spends in a single transaction. Higher AOV only helps ROI if it does not cost more in incentives than it adds in margin.' },
  { term: 'Purchase frequency', def: 'How often a customer buys in a period. Loyalty ROI counts only the additional, profitable visits the program actually caused.' },
  { term: 'Incremental revenue', def: 'Revenue that would not have happened without the program. It is not the same as total revenue from members—much of that would have occurred anyway.' },
  { term: 'Gross profit', def: 'Revenue left after the cost of goods sold. Loyalty is judged on profit, not revenue, because margin is what a program actually earns.' },
  { term: 'Contribution margin', def: 'What a sale contributes after variable costs. Used to weigh incremental behavior against the variable cost of creating it.' },
  { term: 'ROI (return on investment)', def: 'Net gain divided by total cost. For loyalty, it is incremental contribution after full program cost, divided by that cost—shown as a range, not one exact figure.' },
  { term: 'Payback', def: 'How long it takes for the program’s net gain to cover its cost. Shorter payback means less risk.' },
  { term: 'Break-even', def: 'The point where incremental value exactly covers cost. Often expressed as the number of active members or the behavior lift required.' },
  { term: 'Customer lifetime value (CLV)', def: 'The total profit expected from a customer relationship over time, net of the cost to serve and retain them.' },
  { term: 'Redemption', def: 'When a member uses earned points or rewards. Redemption is a real cost and must be modeled, not ignored.' },
  { term: 'Breakage', def: 'Points or rewards that are earned but never redeemed. Breakage lowers cost but should be estimated conservatively, not assumed.' },
  { term: 'Liability', def: 'The accumulated value of unredeemed points a program owes. It sits on the books until redeemed or expired.' },
  { term: 'Cannibalization', def: 'When a program shifts sales you would have made anyway into discounted or rewarded sales, reducing margin without adding revenue.' },
  { term: 'Cohort', def: 'A group of members who share a start point (such as a join month), tracked over time to measure behavior change.' },
  { term: 'Control group', def: 'A comparable group not exposed to the program, used to isolate what loyalty actually caused.' },
  { term: 'Confidence level', def: 'How much to trust an estimate, based on data completeness, source quality, recency, comparability, and sensitivity. Alma uses Directional, Moderate, Strong, and Measured.' },
  { term: 'Sensitivity analysis', def: 'Testing how much the result changes when key inputs change, to reveal which assumptions matter most.' },
  { term: 'ABM (account-based marketing)', def: 'Focusing sales and marketing on a defined set of high-fit accounts rather than a broad audience.' },
  { term: 'ICP (ideal customer profile)', def: 'A description of the accounts most likely to succeed with your product—used to prioritize effort.' },
  { term: 'TAM (total addressable market)', def: 'The full set of companies that could theoretically buy. A starting point for prioritization, not a plan.' },
  { term: 'Churn', def: 'The rate at which customers or members stop buying or participating.' },
  { term: 'Retention', def: 'The rate at which customers or members keep buying or participating. Profitable retention keeps relationships whose value exceeds the cost to retain them.' },
  { term: 'Loyalty vendor', def: 'A software developer or service company that sells loyalty technology or builds loyalty programs for brands. Alma adds an ROI and decision layer for these companies—it does not replace their platform.' },
]
